# Primera vez (Fase de inicialización): Abres tu pgAdmin, dejas el ddl-auto=update y el init.mode=always solo 
# una vez para que se creen las tablas y se metan los productos, cuentas y reportes iniciales del caso vitivinícola.
# Día a día (Fase de desarrollo estable): Cambias el archivo a los valores que te acabo de dar (none y never).

spring.application.name=backend

# 1. Conexión a PostgreSQL (Cambia 'tu_contraseña_de_pgadmin' por la tuya real)
spring.datasource.url=jdbc:postgresql://localhost:5432/db_vitivinicolas
spring.datasource.username=postgres
spring.datasource.password=TU_CONTRASEÑA_AQUI
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Configuración de Hibernate para Postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 'none' le dice a Hibernate: "No crees ni destruyas nada, la DB ya existe en pgAdmin"
spring.jpa.hibernate.ddl-auto=none

# 3. Inicialización de datos de prueba desde data.sql = NO!!
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false

# Mostrar las consultas SQL en la consola (Opcional, muy útil para desarrollo)
spring.jpa.show-sql=true