spring.application.name=backend

# 1. Conexión a PostgreSQL - SOLO CAMBIAR LA CONTRASEÑA
spring.datasource.url=jdbc:postgresql://localhost:5432/db_vitivinicolas
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Configuración de Hibernate para Postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

# 3. Inicialización de datos de prueba
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false

# Mostrar las consultas SQL en la consola
spring.jpa.show-sql=true