spring.application.name=backend

# Render usa la variable PORT. En local usa 8080 por defecto.
server.port=${PORT:8080}

# Base de datos: local por defecto, Neon en producción usando variables de entorno
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/caso_vitivinicolas}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# IMPORTANTE:
# En Neon ya cargaste las tablas y datos, por eso no conviene ejecutar data.sql otra vez.
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false

spring.jpa.show-sql=true

# URL permitida del frontend
app.frontend-url=${FRONTEND_URL:http://localhost:4200}