INSERT INTO producto (codigo, nombre, categoria, ubicacion, stock) VALUES
('VIN-001', 'Malbec Gran Reserva', 'Tintos', 'Cava Principal', 45),
('VIN-002', 'Cabernet Sauvignon', 'Tintos', 'Cava Principal', 60),
('VIN-003', 'Merlot Clasico', 'Tintos', 'Cava Principal', 30),
('VIN-004', 'Syrah Especial', 'Tintos', 'Cava Principal', 25),
('VIN-005', 'Carmenere Reserva', 'Tintos', 'Cava Principal', 40),
('VIN-006', 'Pinot Noir Suave', 'Tintos', 'Cava Principal', 55),
('VIN-007', 'Tannat Robusto', 'Tintos', 'Cava Principal', 20),
('VIN-008', 'Bonarda Joven', 'Tintos', 'Cava Principal', 70),
('VIN-009', 'Sangiovese Italiano', 'Tintos', 'Cava Principal', 15),
('VIN-010', 'Tempranillo Crianza', 'Tintos', 'Cava Principal', 35),
('VIN-011', 'Petit Verdot', 'Tintos', 'Cava Principal', 28),
('VIN-012', 'Cabernet Franc', 'Tintos', 'Cava Principal', 42),
('VIN-013', 'Malbec Roble', 'Tintos', 'Cava Principal', 50),
('VIN-014', 'Blend de Tintas', 'Tintos', 'Cava Principal', 65),
('VIN-015', 'Nero dAvola', 'Tintos', 'Cava Principal', 18),
('VIN-016', 'Shiraz Australiano', 'Tintos', 'Cava Principal', 22),
('VIN-017', 'Zinfandel Intenso', 'Tintos', 'Cava Principal', 33),
('VIN-018', 'Barbera dAsti', 'Tintos', 'Cava Principal', 47),
('VIN-019', 'Nebbiolo Premium', 'Tintos', 'Cava Principal', 12),
('VIN-020', 'Malbec Organico', 'Tintos', 'Cava Principal', 38),
('VIN-021', 'Chardonnay Reserva', 'Blancos', 'Cava Fria', 40),
('VIN-022', 'Sauvignon Blanc', 'Blancos', 'Cava Fria', 55),
('VIN-023', 'Torrontes Saltenio', 'Blancos', 'Cava Fria', 60),
('VIN-024', 'Riesling Seco', 'Blancos', 'Cava Fria', 25),
('VIN-025', 'Viognier Floral', 'Blancos', 'Cava Fria', 30),
('VIN-026', 'Pinot Grigio', 'Blancos', 'Cava Fria', 45),
('VIN-027', 'Semillon Cosecha', 'Blancos', 'Cava Fria', 20),
('VIN-028', 'Chenin Blanc', 'Blancos', 'Cava Fria', 35),
('VIN-029', 'Gewurztraminer', 'Blancos', 'Cava Fria', 15),
('VIN-030', 'Albarinio Fresco', 'Blancos', 'Cava Fria', 50),
('VIN-031', 'Chardonnay Roble', 'Blancos', 'Cava Fria', 28),
('VIN-032', 'Sauvignon Gris', 'Blancos', 'Cava Fria', 32),
('VIN-033', 'Torrontes Tardio', 'Blancos', 'Cava Fria', 40),
('VIN-034', 'Blanco de Blancos', 'Blancos', 'Cava Fria', 22),
('VIN-035', 'Vermentino', 'Blancos', 'Cava Fria', 18),
('VIN-036', 'Muscat Seco', 'Blancos', 'Cava Fria', 25),
('VIN-037', 'Viura Joven', 'Blancos', 'Cava Fria', 48),
('VIN-038', 'Chardonnay Joven', 'Blancos', 'Cava Fria', 62),
('VIN-039', 'Sauvignon Blanc Roble', 'Blancos', 'Cava Fria', 30),
('VIN-040', 'Blanco Dulce', 'Blancos', 'Cava Fria', 55),
('VIN-041', 'Rose de Malbec', 'Rosados', 'Cava Fria', 70),
('VIN-042', 'Rose de Syrah', 'Rosados', 'Cava Fria', 45),
('VIN-043', 'Pinot Noir Rose', 'Rosados', 'Cava Fria', 35),
('VIN-044', 'Rosado de Provence', 'Rosados', 'Cava Fria', 20),
('VIN-045', 'Rose de Cabernet', 'Rosados', 'Cava Fria', 25),
('VIN-046', 'Blush de Uvas', 'Rosados', 'Cava Fria', 50),
('VIN-047', 'Rose Dulce', 'Rosados', 'Cava Fria', 65),
('VIN-048', 'Grenache Rose', 'Rosados', 'Cava Fria', 30),
('VIN-049', 'Rosado Organico', 'Rosados', 'Cava Fria', 15),
('VIN-050', 'Cinsault Rose', 'Rosados', 'Cava Fria', 40),
('VIN-051', 'Rose Espumante', 'Rosados', 'Cava Fria', 22),
('VIN-052', 'Rose de Merlot', 'Rosados', 'Cava Fria', 33),
('VIN-053', 'Tempranillo Rose', 'Rosados', 'Cava Fria', 47),
('VIN-054', 'Rosado Brut', 'Rosados', 'Cava Fria', 28),
('VIN-055', 'Sangiovese Rose', 'Rosados', 'Cava Fria', 18),
('VIN-056', 'Rose de Malbec Roble', 'Rosados', 'Cava Fria', 35),
('VIN-057', 'Rose Seco', 'Rosados', 'Cava Fria', 55),
('VIN-058', 'Rose de Garnacha', 'Rosados', 'Cava Fria', 20),
('VIN-059', 'Rose Cosecha', 'Rosados', 'Cava Fria', 42),
('VIN-060', 'Rosado Premium', 'Rosados', 'Cava Fria', 60),
('VIN-061', 'Espumante Brut', 'Espumantes', 'Deposito Sur', 80),
('VIN-062', 'Extra Brut Imperial', 'Espumantes', 'Deposito Sur', 40),
('VIN-063', 'Demi Sec Dulce', 'Espumantes', 'Deposito Sur', 50),
('VIN-064', 'Brut Nature', 'Espumantes', 'Deposito Sur', 25),
('VIN-065', 'Espumante Rose', 'Espumantes', 'Deposito Sur', 35),
('VIN-066', 'Moscato Espumante', 'Espumantes', 'Deposito Sur', 65),
('VIN-067', 'Champenoise Tradicion', 'Espumantes', 'Deposito Sur', 15),
('VIN-068', 'Espumante Dulce', 'Espumantes', 'Deposito Sur', 70),
('VIN-069', 'Prosecco Estilo', 'Espumantes', 'Deposito Sur', 45),
('VIN-070', 'Espumante Chardonnay', 'Espumantes', 'Deposito Sur', 30),
('VIN-071', 'Extra Brut Roble', 'Espumantes', 'Deposito Sur', 20),
('VIN-072', 'Demi Sec Fino', 'Espumantes', 'Deposito Sur', 38),
('VIN-073', 'Brut Rose', 'Espumantes', 'Deposito Sur', 55),
('VIN-074', 'Espumante Joven', 'Espumantes', 'Deposito Sur', 60),
('VIN-075', 'Cava Clasica', 'Espumantes', 'Deposito Sur', 18),
('VIN-076', 'Espumante de Autor', 'Espumantes', 'Deposito Sur', 22),
('VIN-077', 'Gran Cuvee Brut', 'Espumantes', 'Deposito Sur', 12),
('VIN-078', 'Espumante de Frutos', 'Espumantes', 'Deposito Sur', 40),
('VIN-079', 'Extra Brut Reserva', 'Espumantes', 'Deposito Sur', 33),
('VIN-080', 'Espumante Organico', 'Espumantes', 'Deposito Sur', 28),
('VIN-081', 'Brandy Solera', 'Licores', 'Bodega Norte', 10),
('VIN-082', 'Grappa Aneja', 'Licores', 'Bodega Norte', 15),
('VIN-083', 'Vermouth Rosso', 'Licores', 'Bodega Norte', 45),
('VIN-084', 'Vermouth Blanco', 'Licores', 'Bodega Norte', 40),
('VIN-085', 'Oporto Tawny', 'Fortificados', 'Bodega Norte', 20),
('VIN-086', 'Jerez Seco', 'Fortificados', 'Bodega Norte', 15),
('VIN-087', 'Cognac VSOP', 'Licores', 'Bodega Norte', 8),
('VIN-088', 'Limoncello Artesanal', 'Licores', 'Bodega Norte', 50),
('VIN-089', 'Licor de Cafe', 'Licores', 'Bodega Norte', 35),
('VIN-090', 'Licor de Hierbas', 'Licores', 'Bodega Norte', 25),
('VIN-091', 'Oporto Ruby', 'Fortificados', 'Bodega Norte', 18),
('VIN-092', 'Jerez Cream', 'Fortificados', 'Bodega Norte', 12),
('VIN-093', 'Brandy XO', 'Licores', 'Bodega Norte', 5),
('VIN-094', 'Grappa Blanca', 'Licores', 'Bodega Norte', 22),
('VIN-095', 'Vermouth Extra Dry', 'Licores', 'Bodega Norte', 30),
('VIN-096', 'Licor de Naranja', 'Licores', 'Bodega Norte', 42),
('VIN-097', 'Amaretto Italiano', 'Licores', 'Bodega Norte', 28),
('VIN-098', 'Oporto Blanco', 'Fortificados', 'Bodega Norte', 14),
('VIN-099', 'Anisado Dulce', 'Licores', 'Bodega Norte', 20),
('VIN-100', 'Mistela de Uva', 'Fortificados', 'Bodega Norte', 60);

INSERT INTO cuenta_bancaria (nombre_banco, numero_cuenta, tipo_cuenta, saldo, moneda, fecha_apertura, titular) VALUES
('BCP', '001-456789123', 'CORRIENTE', 80000, 'CLP', '2024-01-15', 'Empresa Vitivinícola'),
('BBVA', '002-987654321', 'AHORRO', 44500, 'CLP', '2024-02-20', 'Empresa Vitivinícola');

INSERT INTO usuario (usuario, password, rol) VALUES
('admin', 'admin123', 'admin'),
('dueno', 'dueno123', 'dueno');

INSERT INTO movimiento_caja (tipo, cuenta, monto, fecha, motivo) VALUES
('Depósito', 'Caja Principal', 1200.00, '2026-05-02', 'Venta de productos'),
('Retiro', 'Cuenta Corriente', 350.00, '2026-05-02', 'Pago de proveedor');